# Generated by Django 4.2.15 on 2024-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutions",
            name="language",
            field=models.PositiveSmallIntegerField(choices=[(0, "Python"), (1, "SQL")]),
        ),
    ]
